#!/system/bin/sh
# An unforunate wrapper script 
# so that the exit code of pppd may be retrieved


# this is a workaround for issue #651747
#trap "/system/bin/sleep 1;exit 0" TERM

PPPD_TTY=$(/system/bin/getprop ril.pppd_tty)
if test -z "$PPPD_TTY" ; then
     /system/bin/setprop ril.pppd_tty /dev/ttyUSB0 
fi
PPPD_PID=

/system/bin/setprop "net.gprs.ppp-exit" ""

/system/bin/log -t pppd "Starting pppd"

/system/bin/pppd $PPPD_TTY 460800 $* call gprs debug kdebug 8 dump

PPPD_EXIT=$?
PPPD_PID=$!

/system/bin/log -t pppd "pppd exited with $PPPD_EXIT"

/system/bin/setprop "net.gprs.ppp-exit" "$PPPD_EXIT"
