#!/system/bin/sh
# Use interface name if linkname is not available
NAME=ppp1

/system/bin/setprop "net.$NAME.remote-ip" "$IPREMOTE"
/system/bin/setprop "net.$NAME.dns1" "$DNS1"
/system/bin/setprop "net.$NAME.dns2" "$DNS2" 
/system/bin/setprop "net.$NAME.local-ip" "$IPLOCAL" 

# give time for properties to be really set 
sleep 1

/system/bin/setprop "ril.pppd.state" "down"
