#!/system/bin/sh
# Use interface name if linkname is not available
NAME=${LINKNAME:-"$1"}

/system/bin/setprop "net.dns1" ""
/system/bin/setprop "net.dns2" "" 
/system/bin/setprop "net.$NAME.local-ip" "" 
/system/bin/setprop "net.$NAME.remote-ip" "" 
/system/bin/setprop "net.$NAME.gw" ""
