#!/system/bin/sh
NAME=ppp1

/system/bin/log -t pppd "start ip up ip remote=$IPREMOTE dns1=$DNS1 dns2=$DNS2 gateway=$IPLOCAL"

/system/bin/log -t pppd "NAME = $NAME"

/system/bin/setprop "net.$NAME.remote-ip" "$IPREMOTE" 
/system/bin/setprop "net.$NAME.dns1" "$DNS1"
/system/bin/setprop "net.$NAME.dns2" "$DNS2" 
/system/bin/setprop "net.$NAME.local-ip" "$IPLOCAL" 

/system/bin/setprop "ril.pppd.state" "up"
