#!/system/bin/sh
NAME=$1
PASS=$2
echo $NAME $PASS
echo "\"$NAME\"    *    \"$PASS\"    *" > /tmp/pap-secrets
echo "*    \"$NAME\"    \"$PASS\"    *" >> /tmp/pap-secrets
echo "\"$NAME\"    *    \"$PASS\"    *" > /tmp/chap-secrets
echo "*    \"$NAME\"    \"$PASS\"    *" >> /tmp/chap-secrets
chmod 700 /tmp/pap-secrets
chmod 700 /tmp/chap-secrets
